bmFtZTogQnVpbGQgYW5kIFB1c2ggRG9ja2VyIEltYWdlCgpvbjoKICB3b3Jr
Zmxvd19kaXNwYXRjaDoKICBwdXNoOgogICAgYnJhbmNoZXM6CiAgICAgIC0g
bWFpbgoKZW52OgogIFJFR0lTVFJZOiBnaGNyLmlvCgpqb2JzOgogIGJ1aWxk
OgogICAgcnVucy1vbjogJ3VidW50dS1sYXRlc3QnCiAgICBzdGVwczoKICAg
ICAgLSBuYW1lOiBTZXQgcmVwb3NpdG9yeSBhbmQgaW1hZ2UgbmFtZSB0byBs
b3dlcmNhc2UKICAgICAgICBydW46IHwKICAgICAgICAgIGVjaG8gIklNQUdF
X05BTUU9JHtJTUFHRV9OQU1FLCx9IiA+PiR7R0lUSFVCX0VOVn0KICAgICAg
ICAgIGVjaG8gIkZVTExfSU1BR0VfTkFNRT1naGNyLmlvLyR7SU1BR0VfTkFN
RSwsfSIgPj4ke0dJVEhVQl9FTlZ9CiAgICAgICAgZW52OgogICAgICAgICAg
SU1BR0VfTkFNRTogJyR7eyBnaXRodWIucmVwb3NpdG9yeSB9fScKCiAgICAg
IC0gdXNlczogYWN0aW9ucy9jaGVja291dEB2MgogICAgICAgIHdpdGg6CiAg
ICAgICAgICBwZXJzaXN0LWNyZWRlbnRpYWxzOiBmYWxzZQogICAgICAgICAg
c3VibW9kdWxlczogcmVjdXJzaXZlCgogICAgICAtIG5hbWU6IFNldCB1cCBE
b2NrZXIgQnVpbGR4CiAgICAgICAgdXNlczogZG9ja2VyL3NldHVwLWJ1aWxk
eC1hY3Rpb25AdjMKCiAgICAgIC0gbmFtZTogTG9nIGluIHRvIHRoZSBDb250
YWluZXIgcmVnaXN0cnkKICAgICAgICB1c2VzOiBkb2NrZXIvbG9naW4tYWN0
aW9uQHYzCiAgICAgICAgd2l0aDoKICAgICAgICAgIHJlZ2lzdHJ5OiAke3sg
ZW52LlJFR0lTVFJZIH19CiAgICAgICAgICB1c2VybmFtZTogJHt7IGdpdGh1
Yi5hY3RvciB9fQogICAgICAgICAgcGFzc3dvcmQ6ICR7eyBzZWNyZXRzLkdJ
VEhVQl9UT0tFTiB9fQoKICAgICAgLSBuYW1lOiBDcmVhdGUgZW1wdHkgYmFz
ZS1idWlsZC1jb250ZXh0IGRpcmVjdG9yeQogICAgICAgIHJ1bjogbWtkaXIg
YmFzZS1idWlsZC1jb250ZXh0CgogICAgICAtIG5hbWU6IEJ1aWxkIGFuZCBw
dXNoCiAgICAgICAgdXNlczogZG9ja2VyL2J1aWxkLXB1c2gtYWN0aW9uQHY2
CiAgICAgICAgd2l0aDoKICAgICAgICAgIGZpbGU6IHNjcmlwdHMvRG9ja2Vy
ZmlsZS5iYXNlCiAgICAgICAgICBjb250ZXh0OiBiYXNlLWJ1aWxkLWNvbnRl
eHQKICAgICAgICAgIHB1c2g6IHRydWUKICAgICAgICAgIHRhZ3M6ICR7eyBl
bnYuRlVMTF9JTUFHRV9OQU1FIH19CgogICAgICAtIG5hbWU6IFNldHVwIE5v
ZGUKICAgICAgICB1c2VzOiAuLy5naXRodWIvYWN0aW9ucy9zZXR1cC1ub2Rl
CgogICAgICAtIG5hbWU6IFNldHVwIEdvCiAgICAgICAgdXNlczogLi8uZ2l0
aHViL2FjdGlvbnMvc2V0dXAtZ28KCiAgICAgIC0gbmFtZTogU2V0dXAgc3Fs
YwogICAgICAgIHVzZXM6IC4vLmdpdGh1Yi9hY3Rpb25zL3NldHVwLXNxbGMK
CiAgICAgIC0gbmFtZTogZ28gaW5zdGFsbCB0b29scwogICAgICAgIHVzZXM6
IC4vLmdpdGh1Yi9hY3Rpb25zL3NldHVwLWdvLXRvb2xzCgogICAgICAtIG5h
bWU6IEJ1aWxkIGFuZCBwdXNoIExpbnV4IGFtZDY0IERvY2tlciBpbWFnZQog
ICAgICAgIHJ1bjogfAogICAgICAgICAgc2V0IC1ldW8gcGlwZWZhaWwKICAg
ICAgICAgIGdvIG1vZCBkb3dubG9hZAogICAgICAgICAgbWFrZSBnZW4vbWFy
ay1mcmVzaAogICAgICAgICAgZXhwb3J0IERPQ0tFUl9JTUFHRV9OT19QUkVS
RVFVSVNJVEVTPXRydWUKICAgICAgICAgIG1ha2UgLWogYnVpbGQvY29kZXJf
bGludXhfYW1kNjQKICAgICAgICAgIC4vc2NyaXB0cy9idWlsZF9kb2NrZXIu
c2ggXAogICAgICAgICAgICAtLWFyY2ggYW1kNjQgXAogICAgICAgICAgICAt
LXRhcmdldCAke3sgZW52LkZVTExfSU1BR0VfTkFNRSB9fSBcCiAgICAgICAg
ICAgIC0tdmVyc2lvbiAidjEuMC4wIiBcCiAgICAgICAgICAgIC0tcHVzaCBc
CiAgICAgICAgICAgIGJ1aWxkL2NvZGVyX2xpbnV4X2FtZDY0Cg==
